all:
  hosts:
    webserver:
      ansible_host: worker_1
      http_directory: /data/webserver
      temp_directory: /temp
      filename: newfile.txt
      file_content: |
        The newly created file is filled with this content.
        This is a new line.

    redis:
      ansible_host: worker_2

    database:
      ansible_host: database

  vars:
    log_directory: /var/log
